"""쇼크 파급 모듈 — **이전됨**: DB 핸들링 계층은 ``nice_dbtool`` 로 옮겼다.

이 패키지는 하위호환 re-export shim 이다 (graph-analysis API·기존 import 유지).
신규 코드는 ``nice_dbtool`` (DB 조립) 과 ``nice_shock`` (순수 전파) 를 직접 쓸 것.
"""
from nice_dbtool import (  # noqa: F401
    AssembledNode,
    Direction,
    DirectionResult,
    EdgeRow,
    ExposedFirm,
    NodeRow,
    Normalize,
    PrimarySelectionResult,
    PropagationInput,
    ScenarioResult,
    ShockResult,
    SubgraphResult,
    VolumeSpec,
    assemble_propagation_input,
    extract_first_target,
    fetch_subgraph,
    make_node_id,
    parse_node_id,
    propagate_shock,
    run_propagation,
    run_scenario,
    run_tariff_shock,
    run_volume_shock,
    select_primary_firms,
)

__all__ = [
    "AssembledNode",
    "Direction",
    "DirectionResult",
    "EdgeRow",
    "ExposedFirm",
    "NodeRow",
    "Normalize",
    "PrimarySelectionResult",
    "PropagationInput",
    "ScenarioResult",
    "ShockResult",
    "SubgraphResult",
    "VolumeSpec",
    "assemble_propagation_input",
    "extract_first_target",
    "fetch_subgraph",
    "make_node_id",
    "parse_node_id",
    "propagate_shock",
    "run_propagation",
    "run_scenario",
    "run_tariff_shock",
    "run_volume_shock",
    "select_primary_firms",
]
